
#
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: blog-geekhub_development
  username: <%= ENV['blog-geekhub_DATABASE_NAME'] %>
  password: <%= ENV['blog-geekhub_DATABASE_PASSWORD'] %>
  encoding: unicode
  host: localhost
  pool: 5

test:
  <<: *default
  database: blog-geekhub_test
  username: <%= ENV['blog-geekhub_DATABASE_NAME'] %>
  password: <%= ENV['blog-geekhub_DATABASE_PASSWORD'] %>
  encoding: unicode
  host: localhost
  pool: 5

production:
  <<: *default
  database: blog-geekhub_production
  username: <%= ENV['blog-geekhub_DATABASE_NAME'] %>
  password: <%= ENV['blog-geekhub_DATABASE_PASSWORD'] %>
# need create "config/application.yml" <%= ENV['blog-geekhub_DATABASE_NAME'] %>
                                    #  <%= ENV['blog-geekhub_DATABASE_PASSWORD'] %>

